### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 6, size is 0

### ISSUE THREAD

**Issue by 2fast2fourier** [2fast2fourier/Something-Awful-Android#28]
``` bash
java.lang.IndexOutOfBoundsException: Invalid index 6, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
at java.util.ArrayList.get(ArrayList.java:304)
at java.util.Collections$UnmodifiableList.get(Collections.java:1050)
at pl.polidea.treeview.AbstractTreeViewAdapter.getTreeId(AbstractTreeViewAdapter.java:115)
at com.ferg.awfulapp.ForumsIndexFragment$AwfulTreeListAdapter.getItemId(Unknown Source)
at android.widget.AbsListView.onSaveInstanceState(AbsListView.java:1667)
at android.view.View.dispatchSaveInstanceState(View.java:12022)
at android.view.ViewGroup.dispatchFreezeSelfOnly(ViewGroup.java:2574)
at android.widget.AdapterView.dispatchSaveInstanceState(AdapterView.java:782)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2560)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2560)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2560)
at android.view.View.saveHierarchyState(View.java:12005)
at android.support.v4.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:1574)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:977)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1185)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:652)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
at com.ferg.awfulapp.widget.AwfulFragmentPagerAdapter.finishUpdate(Unknown Source)
at com.ferg.awfulapp.widget.AwfulViewPager.dataSetChanged(Unknown Source)
at com.ferg.awfulapp.widget.AwfulViewPager$PagerObserver.onChanged(Unknown Source)
at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
at com.ferg.awfulapp.widget.AwfulPagerAdapter.notifyDataSetChanged(Unknown Source)
at com.ferg.awfulapp.widget.AwfulFragmentPagerAdapter.setWidescreen(Unknown Source)
at com.ferg.awfulapp.ForumsIndexActivity.onConfigurationChanged(Unknown Source)
at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:3800)
at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:3973)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by deepakot** [comment]
did you get the solution?
