### ISSUE TITLE
java.lang.IllegalStateException: Could not create an EGL context. eglCreateContext failed with error: EGL_SUCCESS

### ISSUE THREAD

**Issue by 2fast2fourier** [2fast2fourier/Something-Awful-Android#87]
``` bash
java.lang.IllegalStateException: Could not create an EGL context. eglCreateContext failed with error: EGL_SUCCESS
at android.view.HardwareRenderer$GlRenderer.createContext(HardwareRenderer.java:1192)
at android.view.HardwareRenderer$GlRenderer.initializeEgl(HardwareRenderer.java:1044)
at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:979)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1536)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
at android.view.Choreographer.doCallbacks(Choreographer.java:562)
at android.view.Choreographer.doFrame(Choreographer.java:532)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by rraallvv** [comment]
I also got this trace from a crash in one of my apps, it has nothing to do with 2fast2fourier, however I'm curious about whether you has seen this crash again, because [it seems](https://android.stackexchange.com/questions/56327/random-app-crashes-nexus-4-4-3) some bug in the system.

I have Android 4.4.2
