### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap android.content.ContentValues.mValues' on a null object reference

### ISSUE THREAD

**Issue by 2fast2fourier** [2fast2fourier/Something-Awful-Android#90]
``` bash
java.lang.RuntimeException: Unable to destroy activity {com.ferg.awfulapp/com.ferg.awfulapp.PostReplyActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap android.content.ContentValues.mValues' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3478)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3496)
at android.app.ActivityThread.access$1300(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1450)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4998)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap android.content.ContentValues.mValues' on a null object reference
at android.content.ContentValues.<init>(ContentValues.java:62)
at com.ferg.awfulapp.PostReplyFragment.saveReply(PostReplyFragment.java:722)
at com.ferg.awfulapp.PostReplyFragment.autosave(PostReplyFragment.java:319)
at com.ferg.awfulapp.PostReplyFragment.onDestroyView(PostReplyFragment.java:605)
at android.support.v4.app.Fragment.performDestroyView(Fragment.java:1705)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:996)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1921)
at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:335)
at com.ferg.awfulapp.AwfulActivity.onDestroy(AwfulActivity.java:135)
at android.app.Activity.performDestroy(Activity.java:5415)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3465)
... 9 more
java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap android.content.ContentValues.mValues' on a null object reference
at android.content.ContentValues.<init>(ContentValues.java:62)
at com.ferg.awfulapp.PostReplyFragment.saveReply(PostReplyFragment.java:722)
at com.ferg.awfulapp.PostReplyFragment.autosave(PostReplyFragment.java:319)
at com.ferg.awfulapp.PostReplyFragment.onDestroyView(PostReplyFragment.java:605)
at android.support.v4.app.Fragment.performDestroyView(Fragment.java:1705)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:996)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1921)
at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:335)
at com.ferg.awfulapp.AwfulActivity.onDestroy(AwfulActivity.java:135)
at android.app.Activity.performDestroy(Activity.java:5415)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3465)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3496)
at android.app.ActivityThread.access$1300(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1450)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4998)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)

```

**Comment by vytautokas** [comment]
Have you found out the problem?
